FROM python:3.11

WORKDIR /opt

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "manage.py", "migrate"]

CMD ["python3", "manage.py", "collectstatic", "-c", "--no-input"]

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
