version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - pg_dipoma_12_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    image: tempyura/dipoma_12:latest
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static:/opt/static

  frontend:
    image: sermalenk/skypro-front:lesson-36
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static


volumes:
  pg_dipoma_12_data:
  django_static: